baseurl: ''
exclude: ['README.md', '.gitignore']
permalink: pretty

description: codinglead web docs provides information about HTML, CSS and JavaScript.
title: Front End web development - codinglead

collections:
  courses:
      output: true